[package]
name = "axum5"
edition = "2024"
publish = false

[dependencies]
axum = "0.8.6"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
anyhow = "1.0.100"
tower = { version = "0.5.2", features = ["util"] }
