[package]
name = "axum11"
edition = "2024"
publish = false

[dependencies]
axum = "0.8.4"
futures-util = "0.3.31"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5.2", features = ["util"] }

[dev-dependencies]
anyhow = "1.0.99"
